image: python:3.11

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update -y
  - apt-get install curl
  - pip3 install poetry
  - poetry install

stages:
  - prechecks
  - release

license:
  image: docker:latest
  stage: prechecks
  services:
    - name: "docker:dind"
  before_script: [] # We don't need to install our dependencies for this
  script: 
    # Use Google's `addlicence` to check for BSD-2-Clause license 
    # See: https://github.com/google/addlicense
    - docker run --platform=linux/amd64 -v ${PWD}:/src ghcr.io/google/addlicense -v -check -l BSD-2-Clause -c "ChipFlow" -s=only -ignore **/__init__.py **/*.py

lint:
  stage: prechecks
  script: make lint

# Release to PyPi from v* tags
release-from-tag:
    stage: release
    cache: {}
    script:
        - export APP_CODE_VERSION="v$(poetry version -s)"
        - if [[ $APP_CODE_VERSION != $CI_COMMIT_TAG ]] echo "Code version '$APP_CODE_VERSION' does not match tag version '$CI_COMMIT_TAG'"; exit 1;
        - poetry build
        # To publish we will use the `POETRY_PYPI_TOKEN_PYPI` env var
        - poetry publish --dry-run
    only:
        - tags
