image: python:3.11

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .cache/pdm

before_script:
  - pip install --user pdm
  - export PATH=/root/.local/bin:$PATH
  - pdm config install.cache on
  - pdm lock --dev
  - pdm install

stages:
  - prechecks
  - test
  - release

license:
  image: docker:latest
  stage: prechecks
  services:
    - name: "docker:dind"
  before_script: [] # We don't need to install our dependencies for this
  script: 
    # Use Google's `addlicence` to check for BSD-2-Clause license 
    # See: https://github.com/google/addlicense
    - docker run --platform=linux/amd64 -v ${PWD}:/src ghcr.io/google/addlicense -v -check -l BSD-2-Clause -c "ChipFlow" -s=only -ignore **/__init__.py **/*.py

lint:
  stage: prechecks
  script: pdm run lint

test:
  stage: test
  script: pdm run test

# Publish all `main` builds to our GitLab project PyPi repo
publish-to-gitlab:
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^main$/'
  script: pdm publish -r "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi" -u "gitlab-ci-token" -p "${CI_JOB_TOKEN}"
