[tool.poetry]
name = "chipflow-lib"
version = "0.0.0" # Version is set via poetry-dynamic-versioning
description = "ChipFlow common tools."
authors = [
    "Robert Taylor <rob.taylor@chipflow.io>", 
    "Ross Motley <ross.motley@chipflow.io>"
]
license = "BSD-2-Clause"

[tool.poetry.dependencies]
python = "^3.8"
amaranth = { rev = "e3b2ba43162d983da94490b3defaf422630386e9", git = "https://github.com/amaranth-lang/amaranth.git" }
amaranth-soc = { rev = "217d4ea76ad3b3bbf146980d168bc7b3b9d95a18", git = "https://github.com/amaranth-lang/amaranth-soc.git" }
amaranth-boards = { rev = "1d82f2ece15ddcce964b9d3be1d13e8a343537eb", git = "https://github.com/amaranth-lang/amaranth-boards.git" }
amaranth-stdio = { rev = "ae74f176b6ca32b24ab08325159a19318711a5a9", git = "https://github.com/amaranth-lang/amaranth-stdio.git" }
amaranth-orchard = { rev = "49231b8e99b0ccb8e1d04a36d89faa6ee8dafdb7", git = "https://gitlab.com/ChipFlow/amaranth-orchard.git" }
amaranth-vexriscv = {version = "0.0.3.post1.dev0+882a734", source = "chipflow-amaranth-vexriscv"}
yowasp-yosys = "^0.23.dev444"
yowasp-nextpnr-ecp5 = "^0.4.post25.dev361"
tomli = "^2.0.1"
doit = "^0.36.0"

[[tool.poetry.source]]
name = "chipflow-amaranth-vexriscv"
url = "https://gitlab.com/api/v4/projects/33096707/packages/pypi/simple"
default = false
secondary = false

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pycodestyle = "^2.10.0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
