[tool.poetry]
name = "chipflow-lib"
version = "0.0.0" # Version is set via poetry-dynamic-versioning
description = "ChipFlow common tools."
authors = [
    "Robert Taylor <rob.taylor@chipflow.io>", 
    "Ross Motley <ross.motley@chipflow.io>"
]
license = "BSD-2-Clause"

[tool.poetry.scripts]
chipflow = "chipflow_lib.cli:run"

[tool.poetry.dependencies]
python = "^3.8"
amaranth = { git = "https://github.com/amaranth-lang/amaranth.git" }
amaranth-soc = { git = "https://github.com/amaranth-lang/amaranth-soc.git" }
amaranth-boards = { git = "https://github.com/amaranth-lang/amaranth-boards.git" }
amaranth-stdio = { git = "https://github.com/amaranth-lang/amaranth-stdio.git" }
amaranth-orchard = { git = "https://gitlab.com/ChipFlow/amaranth-orchard.git" }
amaranth-vexriscv = { version = "0.0.3.post1.dev0+882a734", source = "chipflow-amaranth-vexriscv"}
yowasp-yosys = "^0.29.0.0"
yowasp-nextpnr-ecp5 = "^0.5.0.0"
yowasp-runtime = "^1.21"
tomli = "^2.0.1"
jsonschema = "^4.17.3"
doit = "^0.36.0"
requests = "^2.30.0"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "chipflow-amaranth-vexriscv"
url = "https://gitlab.com/api/v4/projects/33096707/packages/pypi/simple"
priority = "primary"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pycodestyle = "^2.10.0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
