name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-docs:
    uses: ./.github/workflows/build-docs.yml
    secrets: 
      gh_token: ${{ github.token }}

  deploy-internal:
    runs-on: ubuntu-latest
    steps:

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
