# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Build docs
        run: pdm docs

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
