on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

name: CI
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true

      - name: Install dependencies with multirepo
        uses: chipflow/pdm-multirepo@v1

      - name: Run tests
        run: |
          pdm run test
      - name: Run lints
        run: |
          pdm run lint
      - name: Run doc tests
        run: pdm run test-docs

  license:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check source code licenses
        run: ./tools/license_check.sh

  test-submit:
    uses: ./.github/workflows/test-examples.yml
    secrets:
      CHIPFLOW_API_KEY: ${{ secrets.CHIPFLOW_API_KEY}}
