
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  # allow manual triggering with a given environment
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: environment
name: CI
jobs:

  test:
    environment:
      name: ${{ vars.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true

      - name: Install dependencies with multirepo
        uses: chipflow/pdm-multirepo@v3

      - name: Run tests
        run: pdm run test

      - name: Run lints
        run: pdm run lint

      - name: Run doc tests
        run: pdm run test-docs

  license:
    environment:
      name: ${{ vars.ENVIRONMENT}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check source code licenses
        run: ./tools/license_check.sh

  test-submit:
    uses: ./.github/workflows/test-examples.yml
    with:
      CHIPFLOW_API_ORIGIN: ${{ vars.CHIPFLOW_API_ORIGIN }}
      CHIPFLOW_BACKEND_VERSION: ${{ vars.CHIPFLOW_BACKEND_VERSION }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets:
      CHIPFLOW_API_KEY: ${{ secrets.CHIPFLOW_API_KEY}}

