# .github/workflows/preview.yml
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true

      - name: Install dependencies with multirepo
        uses: chipflow/pdm-multirepo@v3

      - name: Build docs
        run: pdm docs
        if: github.event.action != 'closed'

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/_build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
          pages-base-url: chipflow-lib.docs.chipflow-infra.com
